name = "chinese-horoscope-web"
main = ".open-next/worker.js"
compatibility_date = "2025-09-09"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"

[env.production]
vars = { }

